name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build
        run: make build
